# Generated by Django 3.0.4 on 2020-04-04 18:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prophetcore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(blank=True, choices=[('shared', '已共享的'), ('pre_share', '预共享的')], help_text='系统Slug内容标记', max_length=64, null=True, verbose_name='系统标记')),
                ('created', models.DateTimeField(default=datetime.datetime.now, help_text='该对象的创建日期', verbose_name='创建日期')),
                ('modified', models.DateTimeField(auto_now=True, help_text='该对象的修改日期', verbose_name='修改日期')),
                ('actived', models.NullBooleanField(default=True, help_text='该对象是否为有效资源', verbose_name='已启用')),
                ('deleted', models.NullBooleanField(default=False, editable=False, help_text='该对象是否已被删除', verbose_name='已删除')),
                ('name', models.CharField(help_text='比如: lava-who', max_length=32, verbose_name='测试名称')),
                ('binary', models.CharField(blank=True, default='0.0.0.0', help_text='比如: /path/to/test/target/', max_length=256, verbose_name='文件路径')),
                ('inputtype', models.SlugField(choices=[('file', '文件输入'), ('stdin', '标准输入'), ('argv', '命令行输入'), ('net', '网络输入')], default='file', help_text='默认为文件输入', verbose_name='输入类型')),
                ('creator', models.ForeignKey(help_text='该对象的创建人', on_delete=django.db.models.deletion.PROTECT, related_name='prophetcore_target_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('onidc', models.ForeignKey(blank=True, help_text='该资源所属的节点', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prophetcore_target_onidc', to='prophetcore.Idc', verbose_name='所属节点')),
                ('operator', models.ForeignKey(blank=True, help_text='该对象的修改人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prophetcore_target_operator', to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
                ('tags', models.ManyToManyField(blank=True, help_text='可拥有多个标签,字段数据来自机房选项', limit_choices_to={'flag': 'Target-Tags'}, related_name='prophetcore_target_tags', to='prophetcore.Option', verbose_name='设备标签')),
            ],
            options={
                'verbose_name': '测试目标信息',
                'verbose_name_plural': '测试目标信息',
                'ordering': ['-modified'],
                'abstract': False,
                'default_permissions': ('view', 'add', 'change', 'delete', 'exports'),
                'unique_together': {('onidc', 'name')},
            },
        ),
    ]
