# Generated by Django 3.0.4 on 2020-04-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prophetcore', '0002_target'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='target',
            options={'default_permissions': ('view', 'add', 'change', 'delete', 'exports'), 'ordering': ['-modified'], 'verbose_name': '测试目标', 'verbose_name_plural': '测试目标'},
        ),
        migrations.AddField(
            model_name='target',
            name='cmdargs',
            field=models.CharField(blank=True, default='', help_text='比如: -qling -triton -p 2 -cp 1', max_length=256, null=True, verbose_name='Fuzzing参数'),
        ),
        migrations.AddField(
            model_name='target',
            name='runningpid',
            field=models.CharField(blank=True, help_text='比如: 2706', max_length=32, null=True, verbose_name='进程ID'),
        ),
        migrations.AddField(
            model_name='target',
            name='targetargs',
            field=models.CharField(blank=True, default='', help_text='比如: -d @@', max_length=256, null=True, verbose_name='目标参数'),
        ),
        migrations.AlterField(
            model_name='option',
            name='flag',
            field=models.SlugField(choices=[('', '---------')], help_text='该对象的标记类型,比如：目标类型', max_length=64, verbose_name='标记类型'),
        ),
        migrations.AlterField(
            model_name='target',
            name='binary',
            field=models.CharField(blank=True, default='/home/prophet/binary001', help_text='比如: /path/to/test/target/', max_length=256, verbose_name='文件路径'),
        ),
        migrations.AlterField(
            model_name='target',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='可拥有多个标签,字段数据来自机房选项', limit_choices_to={'flag': 'Target-Tags'}, related_name='prophetcore_target_tags', to='prophetcore.Option', verbose_name='测试对象标签'),
        ),
    ]
